gestion_publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'gestion_publicaciones'

urlpatterns = [
    path('lista-publicaciones', views.PublicacionesList.as_view(),
         name='lista_publicaciones'),
    path('detalle-publicacion/<int:pk>', views.detalle_publicacion,
         name='detalle_publicacion'),
    path('asignar-revisores/<int:pk>', views.mostrar_lista_revisores,
         name='asignar_revisores'),
    path('agregar-revisores/', views.asignar_revisores,
         name='agregar_revisores'),
    path('cambiar-estado-solicitud/<slug:rid64>/<slug:token>/<slug:estado>',
         views.CambiarEstadoSolicitud.as_view(),
         name='cambiar_estado_solicitud'),
    path('enviar-recordatorio/<int:pk>',
         views.recordatorio,
         name='enviar_recordatorio'),
    path('cambiar-revisor/<int:pk>',
         views.cambiar_revisor,
         name='cambiar_revisor'),
]

inifap/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('gestion-publicaciones/', include('gestion_publicaciones.urls')),
]

gestion_publicaciones/models.py
from django.db import models


# Create your models here.
class Revision(models.Model):
    publicacion = models.ForeignKey("publicaciones.Publicacion",
                                    verbose_name=("Publicación"),
                                    on_delete=models.CASCADE,
                                    null=False)
    usuario_revisor = models.ForeignKey("usuarios.Usuario",
                                        verbose_name=("Usuario Revisor"),
                                        on_delete=models.CASCADE,
                                        null=True)
    archivo = models.FileField(upload_to='revisiones/',
                               max_length=100,
                               null=True, blank=True)
    estado = models.ForeignKey("gestion_publicaciones.Estado",
                               verbose_name="Estado",
                               on_delete=models.CASCADE,
                               null=False)


class Estado(models.Model):
    descripcion = models.CharField("Estado de la solicitud", max_length=100)

    def __str__(self):
        return self.descripcion

gestion_publicaciones/forms.py
from django import forms
from django.forms import fields

from usuarios.forms import UsuarioForm
from .models import Revision


class RevisionForm(forms.ModelForm):
    class Meta:
        model = Revision

        exclude = ('publicacion', 'usuario_revisor')

        widgets = {
            'archivo': forms.FileInput(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'})
        }

gestion_publicaciones/views.py
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib import messages
from django.core.mail import EmailMessage
from gestion_publicaciones.models import Estado, Revision
from publicaciones.models import Publicacion
from usuarios.models import Usuario
from django.views.generic import TemplateView
from .token import token_estado


# Create your views here.
class PublicacionesList(ListView):

    model = Publicacion
    template_name = 'publicaciones_list.html'


def detalle_publicacion(request, pk):

    publicacion_seleccionada = get_object_or_404(Publicacion, id=pk)
    revisiones = Revision.objects.filter(publicacion=publicacion_seleccionada)
    if revisiones.count() != 0:

        revisiones_ralizadas = 0
        for revision in revisiones:

            if revision.archivo:

                revisiones_ralizadas = revisiones_ralizadas + 1
        context = {'publicacion': publicacion_seleccionada,
                   'revisiones': revisiones,
                   'estatus': revisiones_ralizadas}
    else:

        context = {'publicacion': publicacion_seleccionada}
    return render(request, 'publicacion_detail.html', context)


def mostrar_lista_revisores(request, pk):

    publicacion_seleccionada = get_object_or_404(Publicacion, id=pk)
    usuarios = Usuario.objects.filter().all()
    revisores = []
    for usuario in usuarios:

        if es_revisor(usuario):

            revisores.append(usuario)
    context = {'publicacion': publicacion_seleccionada,
               'revisores': revisores}
    return render(request, 'revisores_list.html', context)


def es_revisor(user):

    return user.groups.filter(name='Revisor').exists()


def asignar_revisores(request):

    publicacion_seleccionada = get_object_or_404(Publicacion,
                                                 id=int(request.POST['publicacion']))
    if request.method == 'POST':

        contador = 0
        for item in request.POST:

            if request.POST[item] == 'Selected' and contador < 4:

                revisor = Usuario.objects.get(id=int(item))
                revision = Revision.objects.create(publicacion=publicacion_seleccionada,
                                                   usuario_revisor=revisor,
                                                   estado=Estado.objects.get(descripcion='En espera'))
                revision.save()
                contador = contador + 1
                enviar_correo(revision,
                              revisor,
                              publicacion_seleccionada,
                              request)

    return redirect('gestion_publicaciones:detalle_publicacion',
                    pk=publicacion_seleccionada.id)


def enviar_correo(revision, usuario, publicacion, request):

    dominio = get_current_site(request)
    rid = urlsafe_base64_encode(force_bytes(revision.id))
    token = token_estado.make_token(revision)
    if revision.estado == Estado.objects.get(descripcion='En espera'):

        mensaje = render_to_string('solicitud_revision.html',
                                   {
                                       'usuario': usuario,
                                       'dominio': dominio,
                                       'publicacion': publicacion,
                                       'rid': rid,
                                       'revision': revision,
                                       'token': token,
                                       'aceptar': 'Aceptada',
                                       'rechazar': 'Rechazada'
                                   })
        asunto = 'Solicitud de revisión'

    else:

        mensaje = render_to_string('recordatorio_revision.html',
                                   {
                                       'usuario': usuario,
                                       'dominio': dominio,
                                       'publicacion': publicacion
                                   })
        asunto = 'Recordatorio de revisión'

    to = usuario.correo_electronico
    email = EmailMessage(
        asunto,
        mensaje,
        to=[to]
    )
    email.content_subtype = 'html'
    email.send()


class CambiarEstadoSolicitud(TemplateView):

    def get(self, request, *args, **kwargs):

        try:

            rid = urlsafe_base64_decode(kwargs['rid64'])
            estado = kwargs['estado']
            token = kwargs['token']
            revision = Revision.objects.get(id=rid)
        except:

            revision = None
        if revision and token_estado.check_token(revision, token):

            if estado == 'Aceptada':

                revision.estado = Estado.objects.get(descripcion='Aceptada')
                messages.success(self.request,
                                 'Aceptaste la solicitud de revisión')
            else:

                revision.estado = Estado.objects.get(descripcion='Rechazada')
                messages.error(self.request,
                               'Rechazaste la solicitud de revisión')
            revision.save()
        else:
            messages.success(self.request,
                             'Aceptaste la solicitud de revisión')
            messages.error(self.request,
                           'No se realizó la acción correctamente')
        return redirect('usuarios:login')


def recordatorio(request, pk):

    revision = get_object_or_404(Revision, id=pk)
    publicacion = Publicacion.objects.get(id=revision.publicacion.id)
    usuario = Usuario.objects.get(id=revision.usuario_revisor.id)
    enviar_correo(revision, usuario, publicacion, request)
    messages.success(request,
                     'Se envió recordatorio al usuario '+str(usuario))
    return redirect('gestion_publicaciones:detalle_publicacion',
                    pk=publicacion.id)


def cambiar_revisor(request, pk):

    if request.method == 'GET':
        revision = get_object_or_404(Revision, id=pk)
        revisiones = Revision.objects.all().filter(publicacion=revision.publicacion)
        usuarios_disponibles = []
        usuarios_no_disponibles = []
        usuarios = Usuario.objects.all()
        for r in revisiones:

            usuarios_no_disponibles.append(r.usuario_revisor.id)
        for usuario in usuarios:

            if es_revisor(usuario) and usuario.id not in usuarios_no_disponibles:

                usuarios_disponibles.append(usuario)
        context = {'revision': revision,
                   'usuarios_disponibles': usuarios_disponibles,
                   'publicacion': revision.publicacion}
        return render(request, 'asignar_nuevo_revisor.html', context)
    else:

        revision = get_object_or_404(Revision, id=pk)
        usuario = Usuario.objects.get(id=int(request.POST['usuario']))
        revision.usuario_revisor = usuario
        revision.estado = Estado.objects.get(descripcion='En espera')
        revision.save()
        enviar_correo(revision, usuario, revision.publicacion, request)
        return redirect('gestion_publicaciones:detalle_publicacion',
                        pk=revision.publicacion.id)

gestion_publicaciones/templates/asignar_nuevo_revisor.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Lista de Usuarios Revisores
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9">
            Lista de Usuarios Revisores
        </div>
        <div class="col-md-auto">
            <div class="col-md-auto">
                <a class="btn btn-secondary btn-lg" href="{% url 'gestion_publicaciones:detalle_publicacion' publicacion.id %}">Cancelar</a>
            </div>
        </div>
    </div>
</div> 
{% endblock encabezado %}

{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <form action="{% url 'gestion_publicaciones:cambiar_revisor' revision.id %}" method="post">
            {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Primer apellido</th>
                        <th>Segundo apellido</th>
                        <th>Nombre de usuario</th>
                        <th>Correo</th>
                        <th>Selección</th>
                    </tr>
                </thead>
                <tbody>
                    {% for revisor in usuarios_disponibles %}
                    <tr>
                        <td>{{revisor.id}}</td>
                        <td>{{revisor.nombre}}</td>
                        <td>{{revisor.primer_apellido}}</td>
                        <td>
                            {% if revisor.segundo_apellido %}
                                {{revisor.segundo_apellido}}
                            {% else %}
                                Sin segundo apellido       
                            {% endif %}            
                        </td>
                        <td>{{revisor.username}}</td>
                        <td>{{revisor.correo_electronico}}</td>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="{{revisor.id}}" name="usuario">
                            </div>   
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="row justify-content-center">
                <div class="col-2">
                    <button type="submit" class="btn btn-primary btn-lg" id="id_aceptar">Aceptar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock contenido %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    var limite = 1;
    const button = document.getElementById('id_aceptar');
    button.disabled = true;
    $('input.form-check-input').change(function() {
        if($("input:checked").length > limite) {
            this.checked = false;
            button.disabled = false;
        }
        else if($("input:checked").length == limite){
            button.disabled = false; 
        }
        else{
            button.disabled = true; 
        }
    });
</script>
{% endblock js %}

gestion_publicaciones/templates/publicacion_detail.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Detalle de Publicación
{% endblock %}

{% block encabezado %} 
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
    <div class="row align-items-center justify-content-between">
        <div class="col-md-5">
            Detalle de Publicación
        </div>
        <div class="col-md-auto">
            <a class="btn btn-secondary btn-lg" href="{% url 'gestion_publicaciones:lista_publicaciones' %}">Regresar</a>
        </div>
    </div>
</div>
{% endblock %}

{% block contenido %}
    <div id="svg_wrap">
        <section> 
            <h4><b>Datos de la Publicación</b></h4>
            <hr>
            <div class="col-6">
            <p><b>Título: </b>{{publicacion.titulo}}</p>
            <p><b>Autor: </b>{{publicacion.autor}}</p>
            <p><b>Fecha de publicación: </b>{{publicacion.fecha_publicacion}}</p>
            <p>
                <b>Estatus: </b>
                {% if estatus %}
                    {{estatus}} revision(es)
                {% else %}
                    {{publicacion.estatus}}
                {% endif %}
            </p>
        </section>
    </div>
    <br>
    <div id="svg_wrap">
        <section> 
            <h4><b>Revisores de la Publicación</b></h4>
            <hr>
            <div class="col">
            {% if revisiones %}
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Revisor</th>
                            <th>Archivo de revisión</th>
                            <th>Estado de la solicitud</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for revision in revisiones  %}
                        <tr>
                            <td>{{revision.id}}</td>
                            <td>{{revision.usuario_revisor}}</td>
                            <td>
                                {% if revision.archivo %}
                                    {{revision.archivo}}
                                {% else %}
                                    Sin entregar
                                {% endif %}    
                            </td>
                            <td>{{revision.estado.descripcion}}</td>
                            <td>
                                {% if revision.estado.id == 2 %}
                                    <a class="btn btn-success" href="{% url 'gestion_publicaciones:enviar_recordatorio' revision.id %}">
                                        Envíar recordatorio
                                    </a>
                                {% elif revision.estado.id == 3 %}
                                    <a class="btn btn-warning" href="{% url 'gestion_publicaciones:cambiar_revisor' revision.id %}">
                                        Cambiar revisor
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p><b>Esta publicación no tiene revisores asignados. </b></p>
                <a class="btn btn-primary" href="{% url 'gestion_publicaciones:asignar_revisores' publicacion.id %}">
                    Asignar revisores ahora
                </a>
            {% endif %}
            </div>
        </section>
    </div>
    <br>
    <br>
{% endblock contenido %}

gestion_publicaciones/templates/publicaciones_list.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Lista de Publicaciones
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9">
            Lista de Publicaciones
        </div>
    </div>
</div> 
{% endblock encabezado %}

{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Fecha de publicación</th>
                    <th>Estatus</th>
                    <th>Autor</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for publicacion in object_list  %}
                <tr>
                    <td>{{publicacion.id}}</td>
                    <td>{{publicacion.titulo}}</td>
                    <td>{{publicacion.fecha_publicacion}}</td>
                    <td>{{publicacion.estatus}}</td>
                    <td>{{publicacion.autor}}</td>
                    <td>
                        <a class="btn btn-success" href="{% url 'gestion_publicaciones:detalle_publicacion' publicacion.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                            Ver
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}

gestion_publicaciones/templates/recordatorio_revision.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solicitud de revisión</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Recordaorio de revisión</h1>
        </div>
        <div class="row">
            <p>Hola estimado usuario <b>{{usuario}}</b>.
            Se te recuerda que aún no has realizado la revisión de la publicación {{publicacion.titulo}} 
            por lo que te pedimos realizarla lo más pronto posible.</p>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</html>

gestion_publicaciones/templates/revisores_list.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Lista de Usuarios Revisores
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9">
            Lista de Usuarios Revisores
        </div>
        <div class="col-md-auto">
            <div class="col-md-auto">
                <a class="btn btn-secondary btn-lg" href="{% url 'gestion_publicaciones:detalle_publicacion' publicacion.id %}">Cancelar</a>
            </div>
        </div>
    </div>
</div> 
{% endblock encabezado %}

{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <form action="{% url 'gestion_publicaciones:agregar_revisores' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="publicacion" value="{{publicacion.id}}">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Primer apellido</th>
                        <th>Segundo apellido</th>
                        <th>Nombre de usuario</th>
                        <th>Correo</th>
                        <th>Selección</th>
                    </tr>
                </thead>
                <tbody>
                    {% for revisor in revisores %}
                    <tr>
                        <td>{{revisor.id}}</td>
                        <td>{{revisor.nombre}}</td>
                        <td>{{revisor.primer_apellido}}</td>
                        <td>
                            {% if revisor.segundo_apellido %}
                                {{revisor.segundo_apellido}}
                            {% else %}
                                Sin segundo apellido       
                            {% endif %}            
                        </td>
                        <td>{{revisor.username}}</td>
                        <td>{{revisor.correo_electronico}}</td>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="Selected" name="{{revisor.id}}">
                            </div>   
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="row justify-content-center">
                <div class="col-2">
                    <button type="submit" class="btn btn-primary btn-lg" id="id_aceptar">Aceptar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock contenido %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'js/controlador-checkboxes.js' %}"></script>
{% endblock js %}

gestion_publicaciones/templates/solicitud_revision.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solicitud de revisión</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Solicitud de revisión</h1>
        </div>
        <div class="row">
            <p>Hola estimado usuario <b>{{usuario}}</b>,
            se te ha solicitado la revisión de la publicación {{publicacion.titulo}} por lo que
            debes indicarnos lo más pronto posible si deceas aceptar esta Solicitud o rechazarla.</p>
        </div>
        <div class="row">
            <a href="http://{{dominio}}{% url 'gestion_publicaciones:cambiar_estado_solicitud' rid64=rid token=token estado=aceptar %}">Aceptar</a>
            <a href="http://{{dominio}}{% url 'gestion_publicaciones:cambiar_estado_solicitud' rid64=rid token=token estado=rechazar %}">Rechazar</a>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</html>