inifap/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('gestion-publicaciones/', include('gestion_publicaciones.urls')),
]

publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'publicaciones'

urlpatterns = [
    path("", views.InicioView.as_view(), name="inicio"),
    path('descargar-publicacion/<int:id>/',
         views.descargar_publicacion, name="descargar_publicacion"),
    path('visualizar-publicacion/<int:id>/',
         views.visualizar_publicacion, name="visualizar_publicacion"),
    path('mis-publicaciones/', views.MisPublicacionesList.as_view(),
         name='mis_publicaciones'),
    path('mis-publicaciones/nueva/',
         views.PublicacionNueva.as_view(), name='nueva_publicacion'),
    path('revisar-publicaciones/', views.RevisionesList.as_view(),
         name='revisar_publicaciones'),
    path("revisar-publicaciones/detalle/<int:pk>/",
         views.RevisionUpdate.as_view(), name="detalle_revision"),

]

gestion_publicaciones/models.py
from django.db import models


# Create your models here.
class Revision(models.Model):
    publicacion = models.ForeignKey("publicaciones.Publicacion",
                                    verbose_name=("Publicación"),
                                    on_delete=models.CASCADE,
                                    null=False)
    usuario_revisor = models.ForeignKey("usuarios.Usuario",
                                        verbose_name=("Usuario Revisor"),
                                        on_delete=models.CASCADE,
                                        null=True)
    archivo = models.FileField(upload_to='revisiones/',
                               max_length=100,
                               null=True, blank=True)
    estado = models.ForeignKey("gestion_publicaciones.Estado",
                               verbose_name="Estado",
                               on_delete=models.CASCADE,
                               null=False)


class Estado(models.Model):
    descripcion = models.CharField("Estado de la solicitud", max_length=100)

    def __str__(self):
        return self.descripcion

publicaciones/models.py
from django.db import models

# Create your models here.


class Publicacion(models.Model):
    archivo = models.FileField(upload_to='publicaciones/', max_length=100)
    titulo = models.CharField("Título de la publicación", max_length=100)
    fecha_publicacion = models.DateField(
        'Fecha de Publicacion', auto_now_add=True)
    estatus = models.ForeignKey("catalogos.Estatus", verbose_name=(
        "Estatus"), on_delete=models.CASCADE, default=1)
    autor = models.ForeignKey("usuarios.Usuario",
                              verbose_name=("Usuario Postulante"),
                              on_delete=models.CASCADE)

publicaciones/forms.py
from django import forms
from .models import Publicacion


class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        exclude = ('estatus', 'autor', 'fecha_publicacion')
        widgets = {
            'archivo': forms.FileInput(attrs={'class': 'form-control'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Título de la publicación'}),
        }

publicaciones/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from gestion_publicaciones.forms import RevisionForm
from publicaciones.forms import PublicacionForm
from publicaciones.models import Publicacion
from gestion_publicaciones.models import Estado, Revision
from django.shortcuts import redirect
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages


from usuarios.models import Usuario
from django.http import FileResponse, HttpResponse
from django.core.files import File


# Lista de publicaciones
class MisPublicacionesList(PermissionRequiredMixin, ListView):
    permission_required = 'publicaciones.add_publicacion'
    template_name = "mis_publicaciones_list.html"
    model = Publicacion

    def get_queryset(self):
        usuario_actual = self.request.user
        return Publicacion.objects.filter(autor=usuario_actual.id)

# Página de inicio

# Lista de revisiones pendientes


class RevisionesList(PermissionRequiredMixin, ListView):
    permission_required = 'gestion_publicaciones.change_revision'
    template_name = 'publicaciones_revisar_list.html'
    model = Revision

    def get_queryset(self):
        usuario_actual = self.request.user
        return Revision.objects.filter(usuario_revisor=usuario_actual.id)


class InicioView(TemplateView):
    template_name = "inicio.html"


class RevisionUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'gestion_publicaciones.change_revision'
    template_name = 'publicacion_revisar_update.html'
    model = Revision
    form_class = RevisionForm

    def post(self, request, *args, **kwargs):
        form = RevisionForm(request.POST, request.FILES)
        if form.is_valid():
            revision_id = self.kwargs['pk']
            revision_actual = Revision.objects.get(id=revision_id)
            revision_actual.estado = Estado.objects.get(
                id=request.POST['estado'])
            # Si hay algún archivo seleccionado
            if(len(request.FILES) != 0):
                revision_actual.archivo = request.FILES['archivo']
            revision_actual.save()
            messages.success(
                request, 'Tu revisión se ha guardado con éxito')
            return redirect('/revisar-publicaciones/')
        else:
            print("----------- Falló")
            return redirect('/revisar-publicaciones/')


# Nueva publicación
class PublicacionNueva(PermissionRequiredMixin, CreateView):
    permission_required = 'publicaciones.add_publicacion'
    template_name = "publicacion_create.html"
    model = Publicacion
    form_class = PublicacionForm
    success_url = reverse_lazy('publicaciones:mis-publicaciones')

    def post(self, request, *args, **kwargs):
        form = PublicacionForm(request.POST, request.FILES)
        if form.is_valid():
            nueva_publicacion = Publicacion(archivo=request.FILES['archivo'])
            nueva_publicacion.titulo = request.POST['titulo']
            nueva_publicacion.autor = Usuario.objects.filter(
                id=request.user.id).first()
            nueva_publicacion.save()
            messages.success(
                request, 'Tu publicación se ha cargado con éxito y pronto será revisada')
            return redirect('/mis-publicaciones/')
        else:
            return redirect('/mis-publicaciones/')


def handler403(request, *args, **argv):
    response = render('403.html', {},
                      context_instance=RequestContext(request))
    response.status_code = 403
    return response


def descargar_publicacion(request, id):
    publicacion = Publicacion.objects.get(id=id)
    filename = publicacion.archivo.path

    # Para descarga directa
    archivo = open(filename, 'rb')
    myfile = File(archivo)
    response = HttpResponse(myfile, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=' + \
        publicacion.archivo.name
    return response


# por el momento no se implementará, se mantendrá en caso de que el stakeholder quiera
# manejar PDF's posteriormente.
def visualizar_publicacion(request, id):
    publicacion = Publicacion.objects.get(id=id)
    filename = publicacion.archivo.path
    response = FileResponse(open(filename, 'rb'))
    return response

publicaciones/templates/inicio.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
Bienvenido al Sistema de Gestión de Publicaciones Técnicas y Científicas del INIFAP
{% endblock titulo %}


{% block encabezado %}
Bienvenido al Sistema de Gestión de Publicaciones Técnicas y Científicas del INIFAP
{% endblock encabezado %}


{% block contenido %}
{% endblock contenido %}
    
    

publicaciones/templates/mis_publicaciones_list.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Mis Publicaciones 
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9" id="titulo_mis_publicaciones">
            Mis Publicaciones
        </div>
        <div class="col-md-auto">
            <a class="btn btn-primary btn-lg" id="nueva_publicacion" href="{% url 'publicaciones:nueva_publicacion' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Nueva Publicación
            </a>
        </div>
    </div>
</div>
{% endblock encabezado %}


{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Fecha de publicación</th>
                    <th>Estatus</th>
                    <th>Autor</th>
                </tr>
            </thead>
            <tbody>
                {% for publicacion in object_list  %}
                <tr>
                    <td>{{publicacion.id}}</td>
                    <td>{{publicacion.titulo}}</td>
                    <td>{{publicacion.fecha_publicacion}}</td>
                    <td>{{publicacion.estatus}}</td>
                    <td>{{publicacion.autor}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}
    
    

publicaciones/templates/publicacion_create.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Nueva publicación    
{% endblock titulo %}

{% block encabezado %}
Nueva publicación
{% endblock encabezado %}


{% block contenido %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        {{form.titulo}}
    </p>
    <p> 
        {{form.archivo}}
    </p>
    <input type="submit" class="btn btn-primary btn-lg" id="submit" name="submit" value="Enviar archivo a revisión">
</form>
{% endblock contenido %}
    
    

publicaciones/templates/publicacion_revisar_update.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
Detalles de la revisión
{% endblock titulo %}


{% block encabezado %}
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
        <div class="row align-items-center justify-content-between" id="id_encabezado">
            <div class="col-md-8" id="titulo_mis_publicaciones">
                Detalles de la revisión
            </div>
            <div class="col-md-2">
                <a class="btn btn-primary" href="{% url 'publicaciones:descargar_publicacion' revision.publicacion.id %}" id="id_descargar">Descargar publicación</a>            
            </div>
        </div>
</div>


{% endblock encabezado %}

{% block contenido %}
<br>
<div class="card mb-4">
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="svg_wrap">
                <section>
                    <h4><b>Datos de la publicación</b></h4>
                    <hr>
                    <div class="col-6">
                        <b id="id_titulo" >Título:</b> {{revision.publicacion.titulo}}
                        <br>
                        <b id="id_autor">Autor:</b> {{revision.publicacion.autor.nombre}} {{revision.publicacion.autor.primer_apellido}} {{revision.publicacion.autor.segundo_apellido}}
                        <br>
                        
                        {% if revision.archivo.name == '' %}
                            <b id="id_archivo">Última revisión publicada:</b> No hay revisiones aún               
                        {% else %}
                            <b id="id_archivo">Última revisión publicada:</b> {{ revision.archivo.name|slice:"11:" }}
                        {% endif %}
                            
                        <br>
                        <b id="id_subir_revision">Subir nueva revisión:</b> {{form.archivo}}
                        <br>
                        <b id="id_estado">Estado de la revisión:</b> {{form.estado}}
                        <br>
                        <br>
                    </div>
                </section>
            </div>
            <br>
            <button type="submit" class="btn btn-primary" id="id_guardar">Guardar</button>
            <a class="btn btn-secondary" href="{% url 'publicaciones:revisar_publicaciones' %}">Regresar</a>
        </form>
    </div>
</div>
{% endblock contenido %}
    

publicaciones/templates/publicaciones_revisar_list.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Lista de Publicaciones
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9" id="id_revisar_encabezado">
            Revisar publicaciones
        </div>
    </div>
</div> 
{% endblock encabezado %}

{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Autor</th>
                    <th>Fecha de publicación</th>
                    <th>Estatus</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for revision_publicacion in object_list  %}
                <tr>
                    <td>{{revision_publicacion.publicacion.id}}</td>
                    <td>{{revision_publicacion.publicacion.titulo}}</td>
                    <td>{{revision_publicacion.publicacion.autor}}</td>
                    <td>{{revision_publicacion.publicacion.fecha_publicacion}}</td>
                    <td>{{revision_publicacion.estado}}</td>
                    <td>
                        <a class="btn btn-success" href="{% url 'publicaciones:detalle_revision' revision_publicacion.id %}" id="id_ver">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                            Ver
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}