gestion_publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'gestion_publicaciones'

urlpatterns = [
    path('lista-publicaciones', views.PublicacionesList.as_view(),
         name='lista_publicaciones'),
    path('detalle-publicacion/<int:pk>', views.detalle_publicacion,
         name='detalle_publicacion'),
    path('asignar-revisores/<int:pk>', views.mostrar_lista_revisores,
         name='asignar_revisores'),
    path('agregar-revisores/', views.asignar_revisores,
         name='agregar_revisores'),
    path('cambiar-estado-solicitud/<slug:rid64>/<slug:token>/<slug:estado>',
         views.CambiarEstadoSolicitud.as_view(),
         name='cambiar_estado_solicitud'),
    path('enviar-recordatorio/<int:pk>',
         views.recordatorio,
         name='enviar_recordatorio'),
    path('cambiar-revisor/<int:pk>',
         views.cambiar_revisor,
         name='cambiar_revisor'),
]

inifap/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('gestion-publicaciones/', include('gestion_publicaciones.urls')),
]

publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'publicaciones'

urlpatterns = [
    path("", views.InicioView.as_view(), name="inicio"),
    path('descargar-publicacion/<int:id>/',
         views.descargar_publicacion, name="descargar_publicacion"),
    path('visualizar-publicacion/<int:id>/',
         views.visualizar_publicacion, name="visualizar_publicacion"),
    path('mis-publicaciones/', views.MisPublicacionesList.as_view(),
         name='mis_publicaciones'),
    path('mis-publicaciones/nueva/',
         views.PublicacionNueva.as_view(), name='nueva_publicacion'),
    path('revisar-publicaciones/', views.RevisionesList.as_view(),
         name='revisar_publicaciones'),
    path("revisar-publicaciones/detalle/<int:pk>/",
         views.RevisionUpdate.as_view(), name="detalle_revision"),

]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('lista', views.UsuarioList.as_view(), name='lista'),
    path('nuevo', views.UsuarioNuevo.as_view(), name='nuevo'),
    path('eliminar/<int:pk>',
         views.UsuarioEliminar.as_view(),
         name='eliminar'),
    path('modificar/<int:pk>', views.usuario_modificar, name='modificar'),
    path('detalle/<int:pk>', views.usuario_detalle, name='detalle'),
    path('login', views.login, name='login'),
]

catalogos/models.py
from django.db import models

# Create your models here.


class Estatus(models.Model):
    descripcion = models.CharField("Estatus de la publicación", max_length=100)

    def __str__(self):
        return self.descripcion

catalogos/views.py
# Create your views here.

catalogos/templates/base.html
{% load static %}
{% load user_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block titulo %} {% endblock titulo %}</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <!-- CSS Styles -->

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

        
        {% block css %} {% endblock css %}
            
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar navbar-light" style="background-color: #a2f7b5;">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'publicaciones:inicio' %}">Gestión de Artículos</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{request.user.username}} <i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="">Mi perfil</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="">Cerrar sesión</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion" style="background-color: #a2f7b5;">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            
                            {% define "false" as hay_opciones %}
                            
                            {% if request.user|has_group:"Administrador" %}
                                <a class="nav-link" href="{% url 'usuarios:lista' %}">
                                    Administración de usuarios
                                </a>
                                {% define "true" as hay_opciones %}
                            {% endif %}
                            
                            {% if request.user|has_group:"Gestor" %}
                                <a class="nav-link" href="{% url 'gestion_publicaciones:lista_publicaciones' %}">
                                    Gestión de publicaciones
                                </a>    
                                {% define "true" as hay_opciones %}

                            {% endif %}

                            {% if request.user|has_group:"Revisor" %}
                                <a class="nav-link" href="{% url 'publicaciones:revisar_publicaciones' %}" id="id_mis_revisiones">
                                    Mis revisiones
                                </a>    
                                {% define "true" as hay_opciones %}

                            {% endif %}

                            {% if request.user|has_group:"Postulante" %}
                                <a class="nav-link" href="{% url 'publicaciones:mis_publicaciones' %}" id="id_mis_publicaciones">
                                    Mis publicaciones
                                </a>
                                {% define "true" as hay_opciones %}

                            {% endif %}      
                            
                            {% if hay_opciones == "false" %}
                                <p class="nav-link" href="" id="id_no_hay_acciones">
                                    Lo sentimos, tu cuenta de usuario no tiene acciones disponibles
                                </p>
                            {% endif %}
                                
                            
                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer" style="background-color: #a2f7b5;">
                        <div class="small">Instituto Nacional de Investigaciones Forestales Agrícolas y Pecuarias</div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content" {% block colorFondo %}{% endblock colorFondo %}>
                <main>
                    <div class="container-fluid px-4">    
                        <h1 class="mt-4">
                            {% block encabezado %} {% endblock encabezado %}
                        </h1>
                        {% block contenido %} {% endblock contenido %}
                        
                        <!-- <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol> -->

                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Sistema de Gestión de Artículos 2021</div>
                            <!-- Se muetra el logo del SEZAMI en la parte inferior derecha de la pagina -->
                            <div>
                                <img src="{% static 'media/inifap.png' %}" width="100" height="50">
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        {% block mensajes %}     
        {% endblock mensajes %}
            
        {% block js %}
            
        {% endblock js %}
            
    </body>
</html>