inifap/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('gestion-publicaciones/', include('gestion_publicaciones.urls')),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('lista', views.UsuarioList.as_view(), name='lista'),
    path('nuevo', views.UsuarioNuevo.as_view(), name='nuevo'),
    path('eliminar/<int:pk>',
         views.UsuarioEliminar.as_view(),
         name='eliminar'),
    path('modificar/<int:pk>', views.usuario_modificar, name='modificar'),
    path('detalle/<int:pk>', views.usuario_detalle, name='detalle'),
    path('login', views.login, name='login'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField, EmailField
from django.core.validators import validate_email


class Usuario(User):

    nombre = CharField(blank=False, max_length=100)
    primer_apellido = CharField(blank=False, max_length=100)
    segundo_apellido = CharField(max_length=100, blank=True)
    correo_electronico = EmailField(blank=False,
                                    unique=True, validators=[validate_email, ])

    def __str__(self):
        return self.nombre+' '+self.primer_apellido

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

usuarios/forms.py
from django import forms
from .models import Usuario


class UsuarioForm(forms.ModelForm):

    class Meta:

        model = Usuario

        fields = ('nombre', 'primer_apellido', 'segundo_apellido',
                  'correo_electronico', 'username', 'password')

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control',
                                             'placeholder': 'Nombre(s)',
                                             'id': 'id_nombre',
                                             'required': 'required'}),
            'primer_apellido': forms.TextInput(attrs={'class': 'form-control',
                                                      'placeholder': 'Apellido',
                                                      'id': 'id_apellido',
                                                      'required': 'required'}),
            'segundo_apellido': forms.TextInput(attrs={'class': 'form-control',
                                                       'placeholder': 'Apellido',
                                                       'id': 'id_segundo_apellido'}),
            'correo_electronico': forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'Correo electrónico',
                                                         'id': 'id_email',
                                                         'required': 'required'}),
            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Nombre de usuario',
                                               'id': 'id_username',
                                               'required': 'required'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Contraseña',
                                                   'id': 'id_password',
                                                   'required': 'required'}),
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuarios/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls.base import reverse
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from .models import Usuario
from .forms import UsuarioForm


# Create your views here.
class UsuarioList(ListView):

    model = Usuario


class UsuarioNuevo(CreateView):

    model = Usuario
    form_class = UsuarioForm
    extra_context = {'lista_grupos': Group.objects.all(),
                     'titulo': 'Nuevo usuario'}
    success_message = "Usuario creado correctamente"

    def form_valid(self, form):

        user = form.save(commit=True)
        user.groups.clear()
        for item in self.request.POST:

            if self.request.POST[item] == 'on':

                user.groups.add(Group.objects.get(id=int(item)))
        user.save()
        return super().form_valid(form)

    def get_success_url(self):

        return reverse('usuarios:lista')


def login(request):

    if request.method == 'POST':

        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(username=username, password=password)

        if usuario is not None:

            if usuario.is_active:

                auth_login(request, usuario)
                return redirect('publicaciones:inicio')
        else:

            messages.error(request,
                           'El usuario o la contraseña no son correctos')
            return redirect('usuarios:login')
    else:

        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


class UsuarioEliminar(DeleteView):

    model = Usuario
    success_url = reverse_lazy('usuarios:lista')

    def delete(self, request, *args, **kwargs):

        messages.success(self.request, '¡Usuario eliminado exitosamente!')
        return super(UsuarioEliminar, self).delete(request, *args, **kwargs)


def usuario_modificar(request, pk):

    usuario = Usuario.objects.get(id=pk)
    form = UsuarioForm(instance=usuario)
    grupos_usuario = usuario.groups.all()
    if (request.method == 'POST'):

        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():

            usuario = form.save(commit=True)
            usuario.groups.clear()
            for item in request.POST:

                if request.POST[item] == 'on':

                    usuario.groups.add(Group.objects.get(id=int(item)))
            usuario.save()
            return redirect('usuarios:lista')
    context = {'form': form,
               'grupos_usuario': grupos_usuario,
               'lista_grupos': Group.objects.all(),
               'titulo': 'Modificar usuario'}
    return render(request, 'usuarios/usuario_form.html', context)


def usuario_detalle(request, pk):

    usuario = get_object_or_404(Usuario, id=pk)
    grupos = usuario.groups.all()
    return render(request, 'usuarios/usuario_detail.html',
                  {'permisos': grupos,
                   'usuario': usuario})

usuarios/templates/usuarios/usuario_detail.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Detalle del Usuario
{% endblock %}

{% block encabezado %} 
<div class="container">
    <div class="row align-items-center justify-content-between">
        <div class="col-md-5">
            Detalle del Usuario
        </div>
        <div class="col-md-auto">
            <a class="btn btn-warning btn-lg" href="{% url 'usuarios:modificar' usuario.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                Editar
            </a>
        </div>
        <div class="col-md-auto">
            <button onclick="muestraModal('{% url 'usuarios:eliminar' usuario.id %}')" type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#eliminarModal">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
                Eliminar
            </button>
        </div>
    </div>
</div>
{% endblock %}

{% block contenido %}
    <div id="svg_wrap">
        <section> 
            <h4><b>Datos del Usuario</b></h4>
            <hr>
            <div class="col-6">
            <p><b>Nombre(s): </b>{{usuario.nombre}}</p>
            <p><b>Primer apellido: </b> {{usuario.primer_apellido}}</p>
            <p><b>Segundo apellido: </b> {{usuario.segundo_apellido}}</p>
            <p><b>Nombre de usuario: </b> {{usuario.username}}</p>
            <p><b>Correo electrónico: </b>{{usuario.correo_electronico}}</p>
        </section>
    </div>
    <br>
    <div id="svg_wrap">
        <section> 
            <h4><b>Permisos del Usuario</b></h4>
            <hr>
            <div class="col-6">
            {% for permiso in permisos %}
                <p>{{permiso.name}}</p>
            {% endfor %}
            </div>
        </section>
    </div>
    <br>
    <a class="btn btn-secondary btn-lg" href="{% url 'usuarios:lista' %}">Regresar</a>
    <br>
    <br>
    <form id="formEliminar" method="POST">
        {% csrf_token %}
    </form>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/modales.js' %}"></script>
    <script>
        function muestraModal(url){
            Swal.fire({
                title: '¿Está seguro que desea eliminar este usuario?',
                text: "¡No podrás revertir esta acción!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, estoy seguro',
                cancelButtonText: 'Cancelar'
            }).then(function(result) {
                if (result.isConfirmed) {
                    document.getElementById('formEliminar').action = url;
                    document.getElementById('formEliminar').submit();
                }
            })
        }
    </script>
{% endblock %}

usuarios/templates/usuarios/usuario_form.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
{{titulo}}
{% endblock titulo %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">  
{% endblock css %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h1>{{titulo}}</h1>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h4>Datos personales</h4>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <h4>Permisos</h4>
                {% for grupo in lista_grupos %}
                    <div class="row">
                        <div class="col-3">
                            <h6>{{grupo.name}}</h6>
                        </div>
                        <div class="col">
                            <label class="switch" >  
                                {% if grupos_usuario %}
                                    {% if grupo in grupos_usuario %}
                                        <input type="checkbox" name='{{grupo.id}}' checked>
                                    {% else %}
                                        <input type="checkbox" name='{{grupo.id}}'>
                                    {% endif %}
                                {% else %}
                                    <input type="checkbox" name='{{grupo.id}}'>
                                {% endif %}
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <br>
                    {% endfor %}
                <button type="submit" class="btn btn-primary" id="id_guardar">Guardar</button>
                <a class="btn btn-secondary" href="{% url 'usuarios:lista' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock contenido %}

usuarios/templates/usuarios/usuario_list.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Lista de usuarios
{% endblock titulo %}

{% block encabezado %}
<div class="container">
    {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}
    <div class="row align-items-center justify-content-between">
        <div class="col-md-9">
            Lista de usuarios
        </div>
        <div class="col-md-auto">
            <a class="btn btn-primary btn-lg" id="" href="{% url 'usuarios:nuevo' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Nuevo usuario
            </a>
        </div>
    </div>
</div> 
{% endblock encabezado %}

{% block contenido %}
<div class="card mb-4">
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Primer apellido</th>
                    <th>Segundo apellido</th>
                    <th>Nombre de usuario</th>
                    <th>Correo</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in object_list  %}
                <tr>
                    <td>{{usuario.id}}</td>
                    <td>{{usuario.nombre}}</td>
                    <td>{{usuario.primer_apellido}}</td>
                    <td>
                        {% if usuario.segundo_apellido %}
                            {{usuario.segundo_apellido}}
                        {% else %}
                            Sin segundo apellido       
                        {% endif %}            
                    </td>
                    <td>{{usuario.username}}</td>
                    <td>{{usuario.correo_electronico}}</td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{% url 'usuarios:detalle' usuario.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                        </a>
                        <a class="btn btn-warning btn-sm" href="{% url 'usuarios:modificar' usuario.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                        </a>
                        <button onclick="muestraModal('{% url 'usuarios:eliminar' usuario.id %}')" type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#eliminarModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<form id="formEliminar" method="POST">
    {% csrf_token %}
</form>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/modales.js' %}"></script>
    <script>
        function muestraModal(url){
            Swal.fire({
                title: '¿Está seguro que desea eliminar este usuario?',
                text: "¡No podrás revertir esta acción!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, estoy seguro',
                cancelButtonText: 'Cancelar'
            }).then(function(result) {
                if (result.isConfirmed) {
                    document.getElementById('formEliminar').action = url;
                    document.getElementById('formEliminar').submit();
                }
            })
        }
    </script>
{% endblock js %}